-- CORRECTED QUERY 1 (Reporting Tool)
-- This version aligns with Query 2 to eliminate discrepancies
-- Changes made:
-- 1. Removed SHOP TO SHOP_INBOUND to prevent double-counting
-- 2. Renamed SHOP TO SHOP_OUTBOUND to SHOP TO SHOP
-- 3. Removed COUPONCODE IS NOT NULL filter from Sales/Return/Cancel
-- 4. Removed EXPID1 IS NOT NULL filter from Inventory adjustments
-- 5. Changed SHOP TO WH and SHOP TO SHOP to use header timestamp (ch.UPDSTMP)
-- 6. Changed SHOP TO WH to use cd.qty instead of cd.prevqty
-- 7. Made WH TO SHOP cost update log join optional (LEFT OUTER JOIN)

SELECT ff.Product_Group, store_pos_id, store_name, target_store, target_store_name,
       Sub_Inventory, store_type, Item_code, Item_description, Batch_id,
       Transaction_date, Transaction_type, UOM,
       (CASE WHEN ff.Transaction_type IN('SHOP TO WH', 'SHOP TO SHOP') THEN '-' || QTY ELSE TO_CHAR(QTY) END) QTY,
       unit_cost,
       (CASE WHEN ff.Transaction_type IN('SHOP TO WH', 'SHOP TO SHOP') THEN '-' || Total ELSE TO_CHAR(Total) END) Total,
       ERP_AUC, ERP_TOTAL, updated_unit_cost, WINCASH_FORMULA_TOTAL
FROM (
    -- SALES/RETURN/CANCEL Transactions
    SELECT MG.MGNAM Product_Group, O.OFFNO STORE_POS_ID, O.OFFNAM STORE_NAME, 
           '' TARGET_STORE, '' TARGET_STORE_NAME, S.STOCKCPT SUB_INVENTORY,
           O.OFFNAM2 STORE_TYPE, M.MATNO ITEM_CODE, M.MATNAM ITEM_DESCRIPTION, 
           VD.COUPONCODE BATCH_ID, TRUNC(VH.POSDAT) AS TRANSACTION_DATE, 
           (CASE
               WHEN VD.VOUTYPE = 'V' THEN 'SALE'
               WHEN VD.VOUTYPE = 'R' THEN 'RETURN'
               WHEN VD.VOUTYPE = 'S' THEN 'CANCEL'
           END) TRANSACTION_TYPE, 
           MU.UNITNAM UOM, VD.AM QTY, NVL(VD.EMPPRICE, M.EMPPRICE) UNIT_COST,
           ROUND(VD.AM * NVL(VD.EMPPRICE, M.EMPPRICE), 2) TOTAL,
           '' ERP_AUC, '' ERP_TOTAL, '' UPDATED_UNIT_COST, '' WINCASH_FORMULA_TOTAL    
    FROM WINPROD.VOUHDR VH
        INNER JOIN WINPROD.VOUDTL VD ON VH.JOUID = VD.JOUID AND VH.TREEID = VD.TREEID
        INNER JOIN WINPROD.OFFICE O ON O.TREEID = VD.TREEID
        INNER JOIN WINPROD.MATERIAL M ON M.GID = VD.MATID AND M.STOCKCTRL = 'Y'
        INNER JOIN WINPROD.WAREGROUP WG ON WG.GID = VD.WGID 
        INNER JOIN WINPROD.MATGROUP MG ON MG.GID = M.MGID
        INNER JOIN WINPROD.STOCK S ON S.GID = VD.STOCKID
        INNER JOIN WINPROD.MATUNIT MU ON MU.GID = M.UNITID
    WHERE VH.VOUTYPE IN ('V', 'R', 'S')
        AND TRUNC(VH.POSDAT) BETWEEN TO_DATE(#sq(prompt('From', 'Date'))#, 'YYYY-MM-DD') 
                                 AND TO_DATE(#sq(prompt('To', 'Date'))#, 'YYYY-MM-DD')
        -- REMOVED: AND COUPONCODE IS NOT NULL
        
    UNION ALL
    
    -- INVENTORY ADJUSTMENTS (Stock Take)
    SELECT MG.MGNAM Product_Group, O.OFFNO STORE_POS_ID, O.OFFNAM STORE_NAME, 
           '' TARGET_STORE, '' TARGET_STORE_NAME, S.STOCKCPT SUB_INVENTORY,
           O.OFFNAM2 STORE_TYPE, M.MATNO ITEM_CODE, '' ITEM_DESCRIPTION, 
           TO_CHAR(MV.EXPID1) BATCH_ID, TRUNC(MV.UPDSTMP) AS TRANSACTION_DATE, 
           'INV' TRANSACTION_TYPE, 
           MU.UNITNAM UOM, MV.QTY, M.EMPPRICE UNIT_COST,
           ROUND(MV.QTY * M.EMPPRICE, 2) TOTAL, 
           '' ERP_AUC, '' ERP_TOTAL, '' UPDATED_UNIT_COST, '' WINCASH_FORMULA_TOTAL    
    FROM WINPROD.MATMOVE MV
        INNER JOIN WINPROD.MATMOVETYPE MVT ON MV.MVTYPEID = MVT.GID 
            AND MVT.MMTCODE IN ('INV') 
            AND MV.STATUS = 'O' 
            AND MV.MVNO2 IS NOT NULL
        INNER JOIN WINPROD.MATERIAL M ON MV.MATID = M.GID AND M.STOCKCTRL = 'Y'
        INNER JOIN WINPROD.OFFICE O ON MV.TREEID = O.TREEID
        INNER JOIN WINPROD.MATGROUP MG ON MG.GID = M.MGID
        INNER JOIN WINPROD.STOCK S ON S.GID = MV.STOCKID
        INNER JOIN WINPROD.MATUNIT MU ON MU.GID = M.UNITID
    WHERE MV.QTY <> 0 
        AND TRUNC(MV.UPDSTMP) BETWEEN TO_DATE(#sq(prompt('From', 'Date'))#, 'YYYY-MM-DD') 
                                  AND TO_DATE(#sq(prompt('To', 'Date'))#, 'YYYY-MM-DD')
        AND ROUND(MV.QTY * M.EMPPRICE, 2) <> 0
        -- REMOVED: AND EXPID1 IS NOT NULL
        
    UNION ALL
    
    -- WH TO SHOP Transactions
    SELECT MT.MGNAM Product_Group, O.OFFNO STORE_POS_ID, O.OFFNAM STORE_NAME,
           TO_CHAR(S.GID) TARGET_STORE, S.SUPNO TARGET_STORE_NAME,
           SS.STOCKCPT SUB_INVENTORY, O.OFFNAM2 STORE_TYPE,
           M.MATNO ITEM_CODE, M.MATNAM ITEM_DESCRIPTION, '0' BATCH_ID,
           OD.UPDSTMP TRANSACTION_DATE, 'WH TO SHOP' TRANSACTION_TYPE,
           MU.UNITNAM UOM, OD.DELQTY QTY, M.EMPPRICE UNIT_COST, 
           OD.DELQTY * M.EMPPRICE TOTAL,
           TO_CHAR(LGG.UNIT_COST) ERP_AUC, 
           TO_CHAR(LGG.TRANS_QTY * LGG.UNIT_COST) ERP_TOTAL,
           TO_CHAR(LGG.UPDATED_UNIT_COST) UPDATED_UNIT_COST,
           TO_CHAR(LGG.TRANS_QTY * LGG.UPDATED_UNIT_COST) WINCASH_FORMULA_TOTAL
    FROM WINPROD.ORDDTL OD
        INNER JOIN WINPROD.MATERIAL M ON OD.MATNO = M.MATNO AND M.TREEID IN (0, 1)
        INNER JOIN WINPROD.OFFICE O ON OD.TREEID = O.TREEID
        INNER JOIN WINPROD.SUPPLIER S ON OD.SUPID = S.GID
        INNER JOIN WINPROD.MATGROUP MT ON M.MGID = MT.GID
        INNER JOIN WINPROD.MATUNIT MU ON M.UNITID = MU.GID
        INNER JOIN WINPROD.STOCK SS ON OD.STOCKID = SS.GID
        -- CHANGED: Made this LEFT OUTER JOIN to include all WH TO SHOP records
        LEFT OUTER JOIN (
            SELECT LG.WINCASH_ORDER, LG.CSS_ORDER, LG.ITEM_CODE, LG.UNIT_COST,
                   MAX(LG.UPDATED_UNIT_COST) UPDATED_UNIT_COST,
                   SUM(LG.TRANS_QTY) TRANS_QTY
            FROM WINPROD.ETSUAE_COST_UPDATE_LOG LG 
            GROUP BY LG.WINCASH_ORDER, LG.CSS_ORDER, LG.ITEM_CODE, LG.UNIT_COST
        ) LGG ON OD.ORDID = LGG.WINCASH_ORDER AND OD.MATNO = LGG.ITEM_CODE
    WHERE O.STATUS = 'A' 
        AND M.STATUS = 'A' 
        AND OD.ORDSTATUS = 'C'
        AND TRUNC(OD.UPDSTMP) BETWEEN TO_DATE(#sq(prompt('From', 'Date'))#, 'YYYY-MM-DD') 
                                  AND TO_DATE(#sq(prompt('To', 'Date'))#, 'YYYY-MM-DD')
        
    UNION ALL
    
    -- SHOP TO SHOP Transactions (single query, no more OUTBOUND/INBOUND split)
    SELECT MT.MGNAM Product_Group, O.OFFNO STORE_POS_ID, O.OFFNAM STORE_NAME,
           TO_CHAR(O1.OFFNO) TARGET_STORE, O1.OFFNAM TARGET_STORE_NAME,
           SS.STOCKCPT SUB_INVENTORY, O.OFFNAM2 STORE_TYPE,
           M.MATNO ITEM_CODE, M.MATNAM ITEM_DESCRIPTION, '0' BATCH_ID,
           CH.UPDSTMP TRANSACTION_DATE,  -- CHANGED: Use header timestamp
           'SHOP TO SHOP' TRANSACTION_TYPE,  -- CHANGED: Removed _OUTBOUND suffix
           MU.UNITNAM UOM, CD.QTY, M.EMPPRICE UNIT_COST, CD.QTY * M.EMPPRICE TOTAL,
           '' ERP_AUC, '' ERP_TOTAL, '' UPDATED_UNIT_COST, '' WINCASH_FORMULA_TOTAL  
    FROM WINPROD.CMSHDR CH
        INNER JOIN WINPROD.CMSDTL CD ON CH.GID = CD.CMSID
        INNER JOIN WINPROD.MATERIAL M ON CD.MATNO = M.MATNO AND M.TREEID IN (0, 1)
        INNER JOIN WINPROD.OFFICE O ON CD.TREEID = O.TREEID
        INNER JOIN WINPROD.OFFICE O1 ON CD.DSTTREEID = O1.TREEID
        INNER JOIN WINPROD.MATGROUP MT ON M.MGID = MT.GID
        INNER JOIN WINPROD.MATUNIT MU ON M.UNITID = MU.GID
        INNER JOIN WINPROD.STOCK SS ON CD.STOCKID = SS.GID
    WHERE O.STATUS = 'A' 
        AND M.STATUS = 'A' 
        AND O1.STATUS = 'A'
        AND CD.DTLSTATUS = 'C'
        AND TRUNC(CH.UPDSTMP) BETWEEN TO_DATE(#sq(prompt('From', 'Date'))#, 'YYYY-MM-DD') 
                                  AND TO_DATE(#sq(prompt('To', 'Date'))#, 'YYYY-MM-DD')
    -- REMOVED: Second SHOP TO SHOP_INBOUND query
    
    UNION ALL
    
    -- SHOP TO WH Transactions
    SELECT MT.MGNAM Product_Group, O.OFFNO STORE_POS_ID, O.OFFNAM STORE_NAME,
           TO_CHAR(C.GID) TARGET_STORE, C.CLNTNAM1 TARGET_STORE_NAME,
           SS.STOCKCPT SUB_INVENTORY, O.OFFNAM2 STORE_TYPE,
           M.MATNO ITEM_CODE, M.MATNAM ITEM_DESCRIPTION, '0' BATCH_ID,
           CH.UPDSTMP TRANSACTION_DATE,  -- CHANGED: Use header timestamp
           'SHOP TO WH' TRANSACTION_TYPE, MU.UNITNAM UOM,
           CD.QTY QTY,  -- CHANGED: Use CD.QTY instead of CD.PREVQTY
           M.EMPPRICE UNIT_COST, CD.QTY * M.EMPPRICE TOTAL,  -- CHANGED: Use QTY
           '' ERP_AUC, '' ERP_TOTAL, '' UPDATED_UNIT_COST, '' WINCASH_FORMULA_TOTAL   
    FROM WINPROD.CMSHDR CH
        INNER JOIN WINPROD.CMSDTL CD ON CH.GID = CD.CMSID
        INNER JOIN WINPROD.MATERIAL M ON CD.MATNO = M.MATNO AND M.TREEID IN (0, 1)
        INNER JOIN WINPROD.OFFICE O ON CD.TREEID = O.TREEID
        INNER JOIN WINPROD.CLIENT C ON CD.CLIENTID = C.GID
        INNER JOIN WINPROD.STOCK SS ON CD.STOCKID = SS.GID
        INNER JOIN WINPROD.MATGROUP MT ON M.MGID = MT.GID
        INNER JOIN WINPROD.MATUNIT MU ON M.UNITID = MU.GID
    WHERE O.STATUS = 'A' 
        AND M.STATUS = 'A' 
        AND C.STATUS = 'A'
        AND CH.CMSSTATUS IN ('C', 'X')
        AND TRUNC(CH.UPDSTMP) BETWEEN TO_DATE(#sq(prompt('From', 'Date'))#, 'YYYY-MM-DD') 
                                  AND TO_DATE(#sq(prompt('To', 'Date'))#, 'YYYY-MM-DD')
) ff
ORDER BY ff.TRANSACTION_DATE, ff.TRANSACTION_TYPE, ff.STORE_POS_ID, ff.ITEM_CODE;
