-- ENHANCED QUERY 2 (DWH Source with INBOUND/OUTBOUND)
-- This version adds INBOUND and OUTBOUND transaction perspectives
-- to match the business requirement for tracking both sides of transfers

-- Based on user feedback: variance found in SHOP TO SHOP, SHOP TO WH, and WH TO SHOP
-- Solution: Add INBOUND and OUTBOUND designations to Query 2

--WH TO SHOP (INBOUND - from shop perspective)
SELECT 
'WH TO SHOP_INBOUND' TRANSACTION_TYPE, 
TO_CHAR(S.SUPNO) ORIGINATING_STORE_ID, S.SUPNAM1 ORIGINATING_STORE_NAME, 
O.OFFNO RECEIVING_STORE_ID, O.OFFNAM RECEIVING_STORE_NAME, O.OFFNAM2 RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
OD.UPDSTMP TRANSACTION_DATE, 
OD.DELQTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(OD.DELQTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(OH.OrdID) REFERENCENO, D.DELNOTENO CSSREFERENCE
FROM WINPROD.ORDHDR OH
INNER JOIN WINPROD.ORDDTL OD ON OH.ORDiD = OD.ORDID
INNER JOIN WINPROD.MATERIAL M ON OD.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON OD.TREEID = O.TREEID
INNER JOIN WINPROD.SUPPLIER S ON OD.SUPID = S.GID
LEFT OUTER JOIN (SELECT distinct REFNO, DELNOTENO FROM WINPROD.DBOD) D ON D.REFNO = OH.OrdID
WHERE OD.ORDSTATUS='C'
AND TRUNC(OD.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'

UNION ALL

--WH TO SHOP (OUTBOUND - from warehouse perspective)
SELECT 
'WH TO SHOP_OUTBOUND' TRANSACTION_TYPE, 
TO_CHAR(S.SUPNO) ORIGINATING_STORE_ID, S.SUPNAM1 ORIGINATING_STORE_NAME, 
O.OFFNO RECEIVING_STORE_ID, O.OFFNAM RECEIVING_STORE_NAME, O.OFFNAM2 RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
OD.UPDSTMP TRANSACTION_DATE, 
OD.DELQTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(OD.DELQTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(OH.OrdID) REFERENCENO, D.DELNOTENO CSSREFERENCE
FROM WINPROD.ORDHDR OH
INNER JOIN WINPROD.ORDDTL OD ON OH.ORDiD = OD.ORDID
INNER JOIN WINPROD.MATERIAL M ON OD.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON OD.TREEID = O.TREEID
INNER JOIN WINPROD.SUPPLIER S ON OD.SUPID = S.GID
LEFT OUTER JOIN (SELECT distinct REFNO, DELNOTENO FROM WINPROD.DBOD) D ON D.REFNO = OH.OrdID
WHERE OD.ORDSTATUS='C'
AND TRUNC(OD.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'
 
UNION ALL
 
--SHOP TO WH (OUTBOUND - from shop perspective)
SELECT 
'SHOP TO WH_OUTBOUND' TRANSACTION_TYPE, 
TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
TO_CHAR(CLNT.GID) RECEIVING_STORE_ID, CLNT.CLNTNAM1 RECEIVING_STORE_NAME, 'WH' RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
HDR.UPDSTMP TRANSACTION_DATE, 
DTL.QTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(DTL.QTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(CMSID) REFERENCENO, '' CSSREFERENCE
FROM WINPROD.CMSHDR HDR
INNER JOIN WINPROD.CMSDTL DTL ON HDR.GID = DTL.CMSID
INNER JOIN WINPROD.MATERIAL M ON DTL.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON DTL.TREEID = O.TREEID
INNER JOIN WINPROD.CLIENT CLNT ON DTL.CLIENTID = CLNT.GID AND CLNT.STATUS='A'
WHERE HDR.CMSSTATUS IN('C','X') 
AND TRUNC(HDR.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'

UNION ALL

--SHOP TO WH (INBOUND - from warehouse perspective)
SELECT 
'SHOP TO WH_INBOUND' TRANSACTION_TYPE, 
TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
TO_CHAR(CLNT.GID) RECEIVING_STORE_ID, CLNT.CLNTNAM1 RECEIVING_STORE_NAME, 'WH' RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
HDR.UPDSTMP TRANSACTION_DATE, 
DTL.QTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(DTL.QTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(CMSID) REFERENCENO, '' CSSREFERENCE
FROM WINPROD.CMSHDR HDR
INNER JOIN WINPROD.CMSDTL DTL ON HDR.GID = DTL.CMSID
INNER JOIN WINPROD.MATERIAL M ON DTL.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON DTL.TREEID = O.TREEID
INNER JOIN WINPROD.CLIENT CLNT ON DTL.CLIENTID = CLNT.GID AND CLNT.STATUS='A'
WHERE HDR.CMSSTATUS IN('C','X') 
AND TRUNC(HDR.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'

UNION ALL
 
--SHOP TO SHOP (OUTBOUND - from originating shop perspective)
SELECT 
'SHOP TO SHOP_OUTBOUND' TRANSACTION_TYPE, 
TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
OD.OFFNO RECEIVING_STORE_ID, OD.OFFNAM RECEIVING_STORE_NAME, OD.OFFNAM2 RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
HDR.UPDSTMP TRANSACTION_DATE, 
DTL.QTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(DTL.QTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(CMSID) REFERENCENO, '' CSSREFERENCE
FROM WINPROD.CMSHDR HDR
INNER JOIN WINPROD.CMSDTL DTL ON HDR.GID = DTL.CMSID
INNER JOIN WINPROD.MATERIAL M ON DTL.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON DTL.TREEID = O.TREEID
INNER JOIN WINPROD.OFFICE OD ON DTL.DSTTREEID = OD.TREEID
WHERE DTL.DTLSTATUS='C' 
AND TRUNC(HDR.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'

UNION ALL

--SHOP TO SHOP (INBOUND - from receiving shop perspective)
SELECT 
'SHOP TO SHOP_INBOUND' TRANSACTION_TYPE, 
TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
OD.OFFNO RECEIVING_STORE_ID, OD.OFFNAM RECEIVING_STORE_NAME, OD.OFFNAM2 RECEIVING_STORE_TYPE,
M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
HDR.UPDSTMP TRANSACTION_DATE, 
DTL.QTY DELIVERED_QUANTITY, 
NVL(M.Empprice,0) AUC, 
(DTL.QTY * NVL(M.Empprice,0)) TOTAL_COST,
'' SERIAL, '' SUB_REQ_ID, TO_CHAR(CMSID) REFERENCENO, '' CSSREFERENCE
FROM WINPROD.CMSHDR HDR
INNER JOIN WINPROD.CMSDTL DTL ON HDR.GID = DTL.CMSID
INNER JOIN WINPROD.MATERIAL M ON DTL.MATNO = M.MATNO AND M.TREEID IN (0,1) 
INNER JOIN WINPROD.OFFICE O ON DTL.TREEID = O.TREEID
INNER JOIN WINPROD.OFFICE OD ON DTL.DSTTREEID = OD.TREEID
WHERE DTL.DTLSTATUS='C' 
AND TRUNC(HDR.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'
 
UNION ALL
 
-- SALES/RETURN/CANCEL Transactions (no INBOUND/OUTBOUND needed)
SELECT 
        (CASE
            WHEN VD.VOUTYPE = 'V' THEN 'SALE'
            WHEN VD.VOUTYPE = 'R' THEN 'RETURN'
            WHEN VD.VOUTYPE = 'S' THEN 'CANCEL'
        END) TRANSACTION_TYPE, 
        TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
        '' RECEIVING_STORE_ID, '' RECEIVING_STORE_NAME, '' RECEIVING_STORE_TYPE,
        M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
        TRUNC(VH.POSDAT) TRANSACTION_DATE, 
        VD.AM DELIVERED_QUANTITY, 
        NVL(VD.EMPPRICE,M.EMPPRICE) AUC, 
        ROUND(VD.AM * NVL(VD.EMPPRICE,M.EMPPRICE),2) TOTAL_COST,
        SERTXT SERIAL, V2FF.FFVALUE SUB_REQ_ID, TO_CHAR(VD.COUPONCODE) REFERENCENO, '' CSSREFERENCE
    FROM 
        WINPROD.VOUHDR VH
        INNER JOIN WINPROD.VOUDTL VD ON VH.JOUID = VD.JOUID AND VH.TREEID = VD.TREEID
        INNER JOIN WINPROD.OFFICE O ON O.TREEID = VD.TREEID
        INNER JOIN WINPROD.MATERIAL M ON M.GID = VD.MATID AND M.STOCKCTRL='Y'
        INNER JOIN WINPROD.WAREGROUP WG ON WG.GID = VD.WGID 
        INNER JOIN WINPROD.MATGROUP MG ON MG.GID = M.MGID
        INNER JOIN WINPROD.STOCK S ON S.GID = VD.STOCKID
        INNER JOIN WINPROD.MATUNIT MU ON MU.GID = M.UNITID
        LEFT OUTER JOIN WINPROD.VOU2FLEXFIELD V2FF ON V2FF.JOUID = VD.JOUID AND V2FF.DTLID = VD.DTLID AND FFID=24 --24 is sub request id
    WHERE 
        VH.VOUTYPE in ('V','R','S')
        AND TRUNC(VH.POSDAT) BETWEEN '01-NOV-25'  AND '30-NOV-25'
 
UNION ALL
 
-- STOCK TAKE (no INBOUND/OUTBOUND needed)
    SELECT 
        CASE 
            WHEN  MV.QTY < 0 THEN 'STOCK TAKE ADJUSTMENTS PHYSICAL SHORTAGE AND SYSTEM EXCESS' 
            WHEN  MV.QTY > 0 THEN 'STOCK TAKE ADJUSTMENTS PHYSICAL EXCESS and SYSTEM SHORTAGE' 
        END
        TRANSACTION_TYPE,     
        TO_CHAR(O.OFFNO) ORIGINATING_STORE_ID, O.OFFNAM ORIGINATING_STORE_NAME, 
        '' RECEIVING_STORE_ID, '' RECEIVING_STORE_NAME, '' RECEIVING_STORE_TYPE,
        M.MATNO SIC, M.MATNAM SIC_DESCRIPTION, 
        MV.UPDSTMP TRANSACTION_DATE, 
        abs(MV.QTY) DELIVERED_QUANTITY, 
        NVL(M.Empprice,0) AUC, 
        (abs(MV.QTY) * NVL(M.Empprice,0)) TOTAL_COST,
        to_char(SERNOS) SERIAL, '' SUB_REQ_ID, TO_CHAR(MV.EXPID1) REFERENCENO, '' CSSREFERENCE
    FROM WINPROD.MATMOVE MV
        INNER JOIN WINPROD.MATMOVETYPE MVT ON MV.MVTYPEID=MVT.GID AND MVT.MMTCODE IN ('INV') 
                                                AND mv.status ='O' AND MV.MVNO2 is not null
        AND MV.QTY <> 0 --AND mv.EXPID1 IS NOT NULL
        INNER JOIN WINPROD.MATERIAL M ON MV.MATID = M.GID AND M.STOCKCTRL='Y'
        INNER JOIN WINPROD.OFFICE o ON MV.TREEID = O.TREEID
        INNER JOIN WINPROD.MATGROUP MG ON MG.GID = M.MGID
        INNER JOIN WINPROD.STOCK S ON S.GID = MV.STOCKID
        INNER JOIN WINPROD.MATUNIT MU ON MU.GID = M.UNITID
    WHERE 
    trunc(MV.UPDSTMP) BETWEEN '01-NOV-25'  AND '30-NOV-25'
    AND ROUND(MV.QTY * M.EMPPRICE, 2) <> 0;
